import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Navbar } from "@/app/components/Navbar";
import { ThemeProvider } from "@/app/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { SidebarProvider, SidebarTrigger,SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/app/components/app-sidebar"
import { SidebarLeft } from "@/app/components/SidebarLeft"
import { SidebarRight } from "@/app/components/SidebarRight"
 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
          <SidebarLeft />
          <SidebarInset>
          <div className="flex flex-1 flex-col gap-4 p-4">
         {children}
        </div>
          </SidebarInset>
          {/* <SidebarRight /> */}
        </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}



